"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:53:14.288548+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.format("csv")
                      .option("header", "true")
                      .option("inferSchema", "false")
                       .load(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                       .load(f"{bronze_path}/ingestion_timestamp={run_date}"))
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_df = transactions_df.sortWithinPartition("transaction_id", "ingestion_timestamp", ascending=False).dropDuplicates(["transaction_id"], keep="first")
    
    # Read merchants data and cache it
    merchants_df = (spark.read.format("csv")
                   .option("header", "true")
                   .option("inferSchema", "false")
                   .load(merchants_path))
    merchants_df = merchants_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    merchants_df = merchants_df.cache()
    
    # Join transactions with merchants on merchant_id to get merchant_name, category, city
    transactions_df = transactions_df.join(broadcast(merchants_df), on="merchant_id", how="left")
    
    # Add quality flag: mark records with no matching merchant as 'UNMATCHED'
    transactions_df = transactions_df.withColumn("quality_flag", when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN"))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
             .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech/bronze/transactions/"
    bronze_path = "s3://sigma-datatech/silver/transactions/"
    merchants_path = "s3://sigma-datatech/bronze/merchants/"
    output_path = "s3://sigma-datatech/silver/transactions/"
    run_date = "2026-05-27"
    run_id = "run_id_20260527"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)
    
    # Write run metadata summary to a JSON file
    run_metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(run_metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, expr, coalesce, to_date, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Initialize metadata dictionary
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "tables": []
    }

    # Define output paths for each gold table
    merchant_performance_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_path = f"{gold_output_dir}/daily_summary"

    # Build each gold table
    build_merchant_performance(spark, silver_path, merchant_performance_path, run_date)
    build_customer_ltv(spark, silver_path, customer_ltv_path)
    build_daily_summary(spark, silver_path, daily_summary_path, run_date)

    # Append table names to metadata
    run_metadata["tables"].extend(["merchant_performance", "customer_ltv", "daily_summary"])

    # Write metadata to JSON
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data
    silver_transactions = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Read Silver layer merchants data and cache it
    silver_merchants = spark.read.parquet(silver_path).where(col("table_name") == "merchants").cache()

    # Join transactions with merchants
    transactions_with_merchants = silver_transactions.join(
        broadcast(silver_merchants), silver_transactions["merchant_id"] == silver_merchants["merchant_id"], "left"
    )

    # Calculate metrics
    completed_txns = transactions_with_merchants.filter(
    col("status") == "COMPLETED"
)

    merchant_performance = completed_txns.groupBy(
        "merchant_id",
        "merchant_name",
        "category",
        "city",
        "date"
    ).agg(
        sum(coalesce(col("amount").cast(FloatType()), 0)).alias("total_revenue"),
        count("*").alias("txn_count"),
        (
            count(when(col("status") == "FAILED", 1)) /
            count("*") * 100
        ).alias("failure_rate_pct")
    )

    # Write output partitioned by date
    merchant_performance.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer transactions data
    silver_transactions = spark.read.parquet(silver_path)

    # Calculate metrics
    completed_txns = silver_transactions.filter(
        col("status") == "COMPLETED"
    )

    customer_ltv = completed_txns.groupBy(
        "customer_id"
    ).agg(

        sum(
            coalesce(col("amount").cast(FloatType()), 0)
        ).alias("total_spent"),

        count("*").alias("total_txns"),

        avg(
            coalesce(col("amount").cast(FloatType()), 0)
        ).alias("avg_txn_value"),

        min("transaction_date").alias("first_txn_date"),

        max("transaction_date").alias("last_txn_date")
    )

    customer_ltv.write \
        .mode("overwrite") \
        .parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer transactions data for the specific date
    silver_transactions = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Calculate metrics
    daily_summary = silver_transactions.groupBy("date") \
        .agg(
            sum(coalesce(col("amount").cast(FloatType()), 0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write output partitioned by date
    daily_summary.write.mode("overwrite").partitionBy("date").parquet(output_path)
