"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:51:17.452037+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, input_file_name, lit, broadcast, when
from pyspark.sql.types import StructType, StructField, StringType, DecimalType, DateType
import uuid

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read the raw transactions data
    raw_transactions = (spark.read
                       .option("header", "true")
                        .parquet(input_path))
    
    # Add metadata columns
    enriched_transactions = (raw_transactions
                           .withColumn("ingestion_timestamp", current_timestamp())
                           .withColumn("source_file", input_file_name())
                            .withColumn("pipeline_run_id", lit(str(uuid.uuid4()))))
    
    # Partition by ingestion date
    enriched_transactions.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read the bronze layer data with partition pruning
    bronze_df = (spark.read
                .option("header", "true")
                 .parquet(bronze_path)
                .where(f"ingestion_timestamp like '{run_date}%'"))

    # Define schema for casting
    schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("merchant_id", StringType(), True),
        StructField("customer_id", StringType(), True),
        StructField("payment_method", StringType(), True),
        StructField("amount", StringType(), True),
        StructField("transaction_date", StringType(), True),
        StructField("status", StringType(), True),
        StructField("ingestion_timestamp", StringType(), True),
        StructField("source_file", StringType(), True),
        StructField("pipeline_run_id", StringType(), True)
    ])
    
    # Read the merchants data
    merchants_df = (spark.read
                   .option("header", "true")
                   .csv(merchants_path)
                    .hint("broadcast"))

    # Cast columns to correct types
    silver_df = (bronze_df.select([col(c.name).cast(c.dataType) for c in schema])
                .withColumn("amount", col("amount").cast(DecimalType(18,4)))
                 .withColumn("transaction_date", col("transaction_date").cast(DateType())))
    
    # Filter NULL transaction_id and negative amounts
    silver_df = silver_df.filter((col("transaction_id").isNotNull()) & (col("amount") > 0))
    
    # Keep only transaction_date = run_date - 1
    silver_df = silver_df.filter(col("transaction_date") == f"{run_date}-01")
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    silver_df = (silver_df.withColumn("rank", 
                                      when(col("ingestion_timestamp").cast("timestamp")
                                          .cast("long") == col("ingestion_timestamp").cast("timestamp").cast("long").max().over(window.partitionBy("transaction_id"))),
                                      lit("LATEST"))
                .filter(col("rank") == "LATEST")
                .drop("rank"))

    # Join with merchants
    silver_df = silver_df.join(merchants_df, ["merchant_id"], "left")
    
    # Add quality_flag column
    silver_df = silver_df.withColumn("quality_flag", when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    
    # Write the silver layer data
    silver_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Transaction Fee Analysis Pipeline")
             .getOrCreate())
    
    # Define paths and run date
    input_path = "s3://path/to/transactions_raw"
    bronze_path = "s3://path/to/bronze"
    merchants_path = "s3://path/to/payment_fee_lookup"
    output_path = "s3://path/to/silver"
    run_date = "2023-04-01"
    run_id = str(uuid.uuid4())
    
    # Ingest bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform silver layer
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, expr, broadcast
from pyspark.sql.types import DecimalType, StringType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("transaction_date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "transaction_date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count("status").filter(col("status") == "FAILED") / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to output
    merchant_performance_df.repartition("transaction_date").write.mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("status") == "COMPLETED")
    
    # Calculate metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            expr("mode(payment_method) within group (order by count(*) desc)").alias("preferred_payment_method"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date")
        )
    
    # Write to output
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("transaction_date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("transaction_date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id").distinct()).alias("unique_customers"),
            count(col("merchant_id").distinct()).alias("unique_merchants"),
            (count("status").filter(col("status") == "FAILED") / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to output
    daily_summary_df.repartition("transaction_date").write.mode("overwrite").parquet(output_path)

def build_gold(spark, silver_path, gold_output_dir, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("transaction_date") == run_date)
    
    # Fee rates lookup
    fee_rates = {"CREDIT_CARD": 0.02, "DEBIT_CARD": 0.015, "UPI": 0.00}
    fee_rates_df = spark.createDataFrame([(method, rate) for method, rate in fee_rates.items()], ["payment_method", "fee_rate"]).withColumn("fee_rate", col("fee_rate").cast(DecimalType(5,4)))

    # Calculate gross revenue
    gross_revenue = silver_df.filter(col("status") == "COMPLETED").groupBy().agg(sum("amount").alias("gross_revenue"))

    # Calculate transaction volume by payment method
    txn_volume_by_payment_method = silver_df.groupBy("payment_method").agg(count("*").alias("txn_volume"))

    # Calculate fee amount and effective revenue
    fee_analysis_df = txn_volume_by_payment_method.join(fee_rates_df, "payment_method", "left_outer") \
        .withColumn("fee_amount", col("txn_volume") * col("fee_rate") * gross_revenue.gross_revenue) \
       .withColumn("effective_revenue", col("txn_volume") * (1 - coalesce(col("fee_rate"), 0)) * gross_revenue.gross_revenue) \
       .select("payment_method", "txn_volume", "fee_amount", "effective_revenue")

    # Write fee_analysis Gold table
    fee_analysis_df.repartition("payment_method").write.mode("overwrite").parquet(f"{gold_output_dir}/fee_analysis")

def run_gold(spark, silver_path, gold_output_dir, run_date):
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    build_gold(spark, silver_path, gold_output_dir, run_date)

    run_metadata = {
        "run_date": run_date,
        "gold_tables": ["merchant_performance", "customer_ltv", "daily_summary", "fee_analysis"]
    }

    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")
